
services:
  web:
    build: .
    volumes:
      - ./media:/code/media
      - ./static_data:/code/staticfiles
      
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    networks:
          - haproxy

  fetch_datawrapper:
    profiles: ["manual"]
    build: .
    command: python manage.py fetch_datawrapper
    volumes:
      - .:/code
      - ./media:/code/media
      
    env_file:
      - .env
    entrypoint: ["/code/entrypoint.sh"]
    networks:
          - haproxy

volumes:
  static_data:
    driver: local 

networks:
  haproxy:
    external: true
    name: haproxy
