services:
  web:
    build: .
    command: gunicorn archive_webapp.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
      - ./media:/code/media
      - static_data:/code/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: always

  fetch_datawrapper:
    profiles: ["manual"]
    build: .
    command: python manage.py fetch_datawrapper
    volumes:
      - .:/code
      - ./media:/code/media
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]

volumes:
  static_data:
    driver: local 