# Generated by Django 5.1.5 on 2025-02-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
