# Generated by Django 5.1.5 on 2025-02-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chart_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='evergreen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chart',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
