# Generated by Django 5.1.5 on 2025-03-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chart_evergreen_chart_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='tags',
        ),
    ]
