# Generated by Django 5.1.5 on 2025-03-29 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_chart_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ein beschreibender Titel für diesen Datensatz', max_length=255, verbose_name='Titel')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('raw_data', models.TextField(help_text='Die Rohdaten im CSV-Format oder anderen strukturierten Formaten', verbose_name='Rohdaten')),
                ('analysis', models.TextField(blank=True, help_text='Automatisch generierte Analyse der Daten', verbose_name='Analyse')),
                ('header_metadata', models.TextField(blank=True, help_text='Metadaten, die am Anfang der Daten gefunden wurden', verbose_name='Header-Metadaten')),
                ('footer_metadata', models.TextField(blank=True, help_text='Metadaten, die am Ende der Daten gefunden wurden (z.B. Fußnoten)', verbose_name='Footer-Metadaten')),
                ('is_processed', models.BooleanField(default=False, help_text='Gibt an, ob die Daten bereits verarbeitet wurden', verbose_name='Verarbeitet')),
                ('file_type', models.CharField(blank=True, help_text='Ursprünglicher Dateityp der Daten (z.B. CSV, Excel)', max_length=20, verbose_name='Dateityp')),
                ('chart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_sets', to='core.chart', verbose_name='Zugehöriger Chart')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_data_sets', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Chart-Daten',
                'verbose_name_plural': 'Chart-Daten',
                'ordering': ['-created_at'],
            },
        ),
    ]
