# Generated by Django 5.1.5 on 2025-04-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_chartdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='last_modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chart',
            name='patch',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chart',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
