# Generated by Django 5.1.5 on 2025-04-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_chart_last_modified_date_chart_patch_chart_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='patch',
            field=models.BooleanField(default=False),
        ),
    ]
