# Generated by Django 5.1.5 on 2025-04-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_chart_patch'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='regional',
            field=models.BooleanField(default=False),
        ),
    ]
