# Generated by Django 5.1.5 on 2025-05-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_chart_regional'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-Mail-Adresse')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='Bestätigungstoken')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Bestätigt')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Bestätigt am')),
            ],
            options={
                'verbose_name': 'Registrierungsbestätigung',
                'verbose_name_plural': 'Registrierungsbestätigungen',
            },
        ),
    ]
