# Generated by Django 5.1.5 on 2025-05-07 12:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_registrationconfirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationconfirmation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Erstellt am'),
        ),
    ]
