# Generated by Django 5.1.5 on 2025-05-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Der Text, der auf der Kachel angezeigt wird', max_length=100, verbose_name='Titel')),
                ('background_image', models.ImageField(blank=True, help_text='Das Hintergrundbild für die Kachel (optimal: 5:1 Seitenverhältnis)', null=True, upload_to='topic_tiles/', verbose_name='Hintergrundbild')),
                ('background_color', models.CharField(default='#4f80ff', help_text='Hintergrundfarbe als HEX-Code (z.B. #4f80ff), falls kein Bild verwendet wird', max_length=20, verbose_name='Hintergrundfarbe')),
                ('search_terms', models.TextField(help_text='Kommagetrennte Liste von Suchbegriffen, die beim Klick gesucht werden sollen', verbose_name='Suchbegriffe')),
                ('order', models.PositiveIntegerField(default=0, help_text='Position der Kachel (niedrigere Zahlen erscheinen zuerst)', verbose_name='Reihenfolge')),
                ('is_active', models.BooleanField(default=True, help_text='Legt fest, ob die Kachel angezeigt werden soll', verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Themenkachel',
                'verbose_name_plural': 'Themenkacheln',
                'ordering': ['order'],
            },
        ),
    ]
