# Generated by Django 5.1.5 on 2025-05-12 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_topictile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_id', models.CharField(help_text='Die eindeutige ID der Datawrapper-Grafik, die ausgeschlossen werden soll', max_length=10, unique=True, verbose_name='Grafik-ID')),
                ('reason', models.TextField(blank=True, help_text='Optional: Der Grund für die Blacklistung der Grafik', verbose_name='Grund')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_blacklist_entries', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Blacklist-Eintrag',
                'verbose_name_plural': 'Blacklist-Einträge',
                'ordering': ['-created_at'],
            },
        ),
    ]
