# Generated by Django 5.1.5 on 2025-05-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_chartblacklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='title',
            field=models.TextField(),
        ),
    ]
