# Generated by Django 5.1.5 on 2025-05-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_chart_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='chart_id',
            field=models.CharField(max_length=100),
        ),
    ]
