# Generated by Django 5.1.5 on 2025-05-14 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_chart_chart_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedEmailAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Vollständige E-Mail-Adresse, die für die Registrierung erlaubt ist', max_length=254, unique=True, verbose_name='E-Mail-Adresse')),
                ('description', models.CharField(blank=True, help_text="Optionale Beschreibung für diese E-Mail-Adresse (z.B. 'Externer Mitarbeiter')", max_length=255, verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=True, help_text='Legt fest, ob diese E-Mail-Adresse derzeit erlaubt ist', verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_entries', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Erlaubte E-Mail-Adresse',
                'verbose_name_plural': 'Erlaubte E-Mail-Adressen',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='AllowedEmailDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text="E-Mail-Domain, die für die Registrierung erlaubt ist (z.B. 'rnd.de')", max_length=255, unique=True, verbose_name='Domain')),
                ('description', models.CharField(blank=True, help_text="Optionale Beschreibung für diese Domain (z.B. 'RedaktionsNetzwerk Deutschland')", max_length=255, verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=True, help_text='Legt fest, ob diese Domain derzeit erlaubt ist', verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_domain_entries', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Erlaubte E-Mail-Domain',
                'verbose_name_plural': 'Erlaubte E-Mail-Domains',
                'ordering': ['domain'],
            },
        ),
    ]
