# Generated by Django 5.1.5 on 2025-05-19 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_allowedemailaddress_allowedemaildomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='topictile',
            name='inherit_parent_search',
            field=models.BooleanField(default=True, help_text='Wenn aktiviert, werden die Suchbegriffe der übergeordneten Kachel zu den eigenen hinzugefügt', verbose_name='Eltern-Suchbegriffe erben'),
        ),
        migrations.AddField(
            model_name='topictile',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Falls dies eine Unterkachel ist, wähle die übergeordnete Themenkachel aus', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.topictile', verbose_name='Übergeordnete Kachel'),
        ),
        migrations.AddField(
            model_name='topictile',
            name='show_in_main',
            field=models.BooleanField(default=True, help_text='Legt fest, ob die Kachel auf der Hauptseite angezeigt werden soll (für Unterkacheln typischerweise deaktiviert)', verbose_name='Auf Hauptseite anzeigen'),
        ),
    ]
