# Generated by Django 5.1.5 on 2025-05-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_topictile_inherit_parent_search_topictile_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='author',
            field=models.CharField(blank=True, help_text='Name des Autors aus den Datawrapper-Metadaten', max_length=255, verbose_name='Autor'),
        ),
    ]
