# Generated by Django 5.1.5 on 2025-05-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_chart_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='author_email',
            field=models.EmailField(blank=True, help_text='E-Mail-Adresse des Autors aus den Datawrapper-Metadaten', max_length=254, verbose_name='Autor E-Mail'),
        ),
    ]
