# Generated by Django 5.1.5 on 2025-05-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_chart_author_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='archive',
            field=models.BooleanField(default=False, help_text="Wert des custom-fields 'archiv' aus den Datawrapper-Metadaten", verbose_name='Archiviert'),
        ),
    ]
