# Generated by Django 5.1.5 on 2025-05-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_chart_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='pic_url_full',
            field=models.URLField(blank=True, help_text='URL zum vollständigen Thumbnail-Bild', verbose_name='Bild-URL (Vollbild)'),
        ),
        migrations.AddField(
            model_name='chart',
            name='pic_url_small',
            field=models.URLField(blank=True, help_text='URL zum kleinen Thumbnail-Bild', verbose_name='Bild-URL (Klein)'),
        ),
        migrations.AddField(
            model_name='chart',
            name='preview_url',
            field=models.URLField(blank=True, help_text='URL zur Vorschau der Grafik (publicUrl)', verbose_name='Vorschau-URL'),
        ),
    ]
