# Generated by Django 5.1.5 on 2025-05-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_chart_pic_url_full_chart_pic_url_small_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='iframe_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
