# Generated by Django 5.1.5 on 2025-05-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_increase_iframe_url_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='folder',
            field=models.TextField(blank=True, help_text='Kommagetrennte Liste der Ordner und Unterordner, in denen die Grafik liegt', verbose_name='Ordner'),
        ),
    ]
