# Generated by Django 5.1.5 on 2025-05-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_add_folder_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topictile',
            name='search_terms',
            field=models.TextField(help_text="Kommagetrennte Liste von Suchbegriffen, die beim Klick gesucht werden sollen. Spezielle Feldfilter können mit der Syntax 'feld: Wert' angegeben werden, z.B. 'tag: Bildung' filtert nur nach dem Tag 'Bildung'. Unterstützte Felder: tag, title, description, notes, author, chart_id.", verbose_name='Suchbegriffe'),
        ),
    ]
