# Generated by Django 5.1.5 on 2025-05-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_topictile_search_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='topictile',
            name='exact_tag_search',
            field=models.BooleanField(default=False, help_text="Wenn aktiviert, werden Tag-Suchbegriffe exakt gesucht (z.B. 'Sachsen' findet nicht 'Niedersachsen')", verbose_name='Exakte Tag-Suche'),
        ),
    ]
