# Generated by Django 5.1.5 on 2025-05-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_topictile_exact_tag_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='topictile',
            name='user_message',
            field=models.TextField(blank=True, help_text='Optionale Nachricht, die Benutzern angezeigt wird, wenn sie diesen Themenbereich betreten', verbose_name='Benutzerhinweis'),
        ),
    ]
