# Generated by Django 5.1.5 on 2025-05-27 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_topictile_user_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Kurzer Titel für die Nachricht', max_length=200, verbose_name='Titel')),
                ('message', models.TextField(help_text='Die Nachricht, die den Benutzern angezeigt werden soll', verbose_name='Nachricht')),
                ('message_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warnung'), ('error', 'Fehler'), ('success', 'Erfolg')], default='info', help_text='Bestimmt die Farbe und das Icon der Nachricht', max_length=20, verbose_name='Nachrichtentyp')),
                ('is_active', models.BooleanField(default=True, help_text='Legt fest, ob die Nachricht angezeigt werden soll', verbose_name='Aktiv')),
                ('show_on_main_archive', models.BooleanField(default=True, help_text='Zeigt die Nachricht auf der Hauptarchiv-Seite (/archive) an', verbose_name='Auf Hauptarchiv anzeigen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('valid_until', models.DateTimeField(blank=True, help_text='Optional: Datum bis wann die Nachricht angezeigt werden soll', null=True, verbose_name='Gültig bis')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_system_messages', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Systemnachricht',
                'verbose_name_plural': 'Systemnachrichten',
                'ordering': ['-created_at'],
            },
        ),
    ]
