# Generated by Django 5.1.5 on 2025-05-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_systemmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmessage',
            name='show_on_index',
            field=models.BooleanField(default=False, help_text='Zeigt die Nachricht auf der Startseite (Login/Registrierung) an', verbose_name='Auf Startseite anzeigen'),
        ),
    ]
